#############################################################################
#           Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#############################################################################
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/deviensdev

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

  # Deploy to preprod
  test_and_deploy_preprod:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT

      - run:
          name: Add to known_hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy
          command: |
            git remote add preprod dokku@$SSH_HOST:deviensdev-preprod
            git push preprod

  # Deploy to prod
  test_and_deploy_prod:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT

      - run:
          name: Add to known_hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy
          command: |
            git remote add prod dokku@$SSH_HOST:deviensdev-prod
            git push prod

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - build

      - test_and_deploy_preprod:
          requires:
            - build

          filters:
            branches:
              only: develop

      - test_and_deploy_prod:
          requires:
            - build

          filters:
            branches:
              only: master
