name: CD

on:
  push:
    branches:
    - migration

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install aws cli
      run: sudo apt install awscli
    - name: config aws
      run: |
        mkdir ~/.aws
        echo "[default]" > ~/.aws/config
        echo "region = eu-west-3" >> ~/.aws/config
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_KEY_ID}}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_ACCESS_KEY}}" >> ~/.aws/credentials
    - name: set github token
      run: |
        echo "DEVIENSDEV_GITHUB_TOKEN=${{ secrets.DEVIENSDEV_GITHUB_TOKEN }}" > .env
    - name: remove preinstalled nodejs 12
      run: sudo apt remove nodejs -y
    - name: install nodejs 10 and last npm
      run: |
        wget -qO- https://deb.nodesource.com/setup_10.x | sudo -E bash -
        sudo apt install nodejs
        sudo npm install -g npm
    - name: install nodejs dependancies
      run: |
        npm install
    - name: build static files
      run: |
        npm run build
    - name: upload
      run: |
        aws s3 sync public/ s3://deviens.dev
